"""
FastAPI Endpoints for GutBut Content Intelligence Pipeline
==========================================================
  POST /scrape        — Scrape a URL (auto-detects source type)
  POST /score         — Score raw content with trust engine
  GET  /pipeline-report — Return most recent pipeline report

Run with:
    uvicorn api:app --reload --port 8000
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, HttpUrl
from typing import Optional
import json
from pathlib import Path

from scrapers import scrape_pubmed, scrape_blog, scrape_youtube
from trust_engine import calculate_trust_score
from utils import extract_domain

app = FastAPI(
    title="GutBut Content Intelligence API",
    description="Multi-source health content ingestion and trust scoring pipeline.",
    version="1.0.0",
)

OUTPUT_DIR = Path("output")
OUTPUT_DIR.mkdir(exist_ok=True)


# ── Request / Response Models ─────────────────────────────────────────────────

class ScrapeRequest(BaseModel):
    url: str
    source_type: Optional[str] = None  # "blog" | "youtube" | "pubmed" | None (auto-detect)

class ScoreRequest(BaseModel):
    source_url: str
    source_type: str
    author: Optional[str] = None
    published_date: Optional[str] = None
    content: str
    citation_count: int = 0
    transcript_available: bool = True


# ── Helpers ───────────────────────────────────────────────────────────────────

def _detect_type(url: str) -> str:
    if "youtube.com" in url or "youtu.be" in url:
        return "youtube"
    if "pubmed" in url or "ncbi.nlm.nih.gov" in url:
        return "pubmed"
    return "blog"


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {
        "service": "GutBut Content Intelligence API",
        "version": "1.0.0",
        "endpoints": ["/scrape", "/score", "/pipeline-report"],
    }


@app.post("/scrape")
def scrape_endpoint(req: ScrapeRequest):
    """
    Scrape a single URL and return its trust-scored structured record.
    Automatically detects whether the URL is a blog, YouTube video, or PubMed article.
    """
    source_type = req.source_type or _detect_type(req.url)

    try:
        if source_type == "youtube":
            results = scrape_youtube([req.url])
        elif source_type == "pubmed":
            # Extract PMID or treat as query
            import re
            pmid_match = re.search(r'/(\d+)/?', req.url)
            if pmid_match:
                from scrapers.pubmed_scraper import fetch_pubmed_record
                record = fetch_pubmed_record(pmid_match.group(1))
                results = [record] if record else []
            else:
                results = scrape_pubmed([req.url], max_per_query=1)
        else:
            results = scrape_blog([req.url])

        if not results:
            raise HTTPException(status_code=422, detail="Scraping returned no results.")

        return {"status": "success", "source_type": source_type, "result": results[0]}

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/score")
def score_endpoint(req: ScoreRequest):
    """
    Score raw content using the trust engine directly (no scraping).
    Useful for testing the scorer or scoring content from other sources.
    """
    try:
        domain = extract_domain(req.source_url)
        result = calculate_trust_score(
            source_url=req.source_url,
            source_type=req.source_type,
            author=req.author,
            published_date=req.published_date,
            content=req.content,
            domain=domain,
            citation_count=req.citation_count,
            transcript_available=req.transcript_available,
        )
        return {"status": "success", "scoring_result": result}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/pipeline-report")
def pipeline_report_endpoint():
    """
    Return the most recent pipeline_report.json generated by main.py.
    """
    report_path = OUTPUT_DIR / "pipeline_report.json"
    if not report_path.exists():
        raise HTTPException(
            status_code=404,
            detail="No pipeline report found. Run main.py first to generate one.",
        )
    with open(report_path, "r") as f:
        report = json.load(f)
    return {"status": "success", "report": report}
